# Site settings
title: Ian Mortier - Designer
email: ianmortier@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ian Mortier is a designer who lives in Canada and works at Shopify. Is dope.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ianmortier.com" # the base hostname & protocol for your site
twitter_username: heal
github_username:  healthcare

# Build settings
markdown: kramdown
